// <auto-generated />
using System;
using BarberBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberBooking.Infrastructure.Migrations
{
    [DbContext(typeof(BarberBookingDbContext))]
    [Migration("20260309121256_RefactorToServiceFirst")]
    partial class RefactorToServiceFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarberBooking.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "EndTime");

                    b.HasIndex("BarberId", "StartTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.BarberService", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("char(36)");

                    b.HasKey("ServiceId", "BarberId");

                    b.HasIndex("BarberId");

                    b.ToTable("BarberService");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.BarberWorkingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "Date");

                    b.HasIndex("BarberId", "DayOfWeek");

                    b.ToTable("BarberWorkingDays", (string)null);
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.BlockedSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "StartTime");

                    b.ToTable("BlockedSlots");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.BarberService", b =>
                {
                    b.HasOne("BarberBooking.Domain.Entities.Barber", "Barber")
                        .WithMany("BarberServices")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberBooking.Domain.Entities.Service", "Service")
                        .WithMany("BarberServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.BarberWorkingDay", b =>
                {
                    b.OwnsOne("BarberBooking.Domain.ValueObjects.WorkingHours", "WorkingHours", b1 =>
                        {
                            b1.Property<Guid>("BarberWorkingDayId")
                                .HasColumnType("char(36)");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("time(6)")
                                .HasColumnName("EndTime");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("time(6)")
                                .HasColumnName("StartTime");

                            b1.HasKey("BarberWorkingDayId");

                            b1.ToTable("BarberWorkingDays");

                            b1.WithOwner()
                                .HasForeignKey("BarberWorkingDayId");
                        });

                    b.Navigation("WorkingHours")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.Barber", b =>
                {
                    b.Navigation("BarberServices");
                });

            modelBuilder.Entity("BarberBooking.Domain.Entities.Service", b =>
                {
                    b.Navigation("BarberServices");
                });
#pragma warning restore 612, 618
        }
    }
}
